from Scripts.PlayerCharacter.Base.character_base import Character
import pygame
from Scripts.game_constants import GameConstants
from Scripts.PlayerCharacter.Sasuke.State.sasuke_state_machine import SasukeStateMachine
class SasukeCharacter(Character):
  def __init__(self,game_scene,player_id,x,y,screen_surface,target):
    super().__init__(game_scene,player_id,x,y,screen_surface,target)
    self.rect = pygame.Rect((x,y,GameConstants.SASUKE_WIDTH_RECT,GameConstants.SASUKE_HEIGHT_RECT))
    self.state_machine = SasukeStateMachine(self,screen_surface)
  
  def start(self):
    self.idle_spritesheet = [self.handle_image(pygame.image.load(GameConstants.SASUKE_IDLE_SPRITESHEET_SOURCE[0]).convert_alpha(),34,50,6,GameConstants.SASUKE_IDLE_SPRITESHEET_SOURCE[1]),GameConstants.SASUKE_IDLE_SPRITESHEET_SOURCE[1],GameConstants.SASUKE_IDLE_SPRITESHEET_SOURCE[2],GameConstants.SASUKE_IDLE_SPRITESHEET_SOURCE[3],GameConstants.SASUKE_IDLE_SPRITESHEET_SOURCE[4],GameConstants.SASUKE_IDLE_SPRITESHEET_SOURCE[5]]
    self.move_spritesheet = [self.handle_image(pygame.image.load(GameConstants.SASUKE_MOVE_SPRITESHEET_SOURCE[0]).convert_alpha(),48,48,6,GameConstants.SASUKE_MOVE_SPRITESHEET_SOURCE[1]),GameConstants.SASUKE_MOVE_SPRITESHEET_SOURCE[1],GameConstants.SASUKE_MOVE_SPRITESHEET_SOURCE[2],GameConstants.SASUKE_MOVE_SPRITESHEET_SOURCE[3],GameConstants.SASUKE_MOVE_SPRITESHEET_SOURCE[4],GameConstants.SASUKE_MOVE_SPRITESHEET_SOURCE[5]]
    self.jump_spritesheet= [self.handle_image(pygame.image.load(GameConstants.SASUKE_JUMP_SPRITESHEET_SOURCE[0]).convert_alpha(),33,53,2,GameConstants.SASUKE_JUMP_SPRITESHEET_SOURCE[1]),GameConstants.SASUKE_JUMP_SPRITESHEET_SOURCE[1],GameConstants.SASUKE_JUMP_SPRITESHEET_SOURCE[2],GameConstants.SASUKE_JUMP_SPRITESHEET_SOURCE[3],GameConstants.SASUKE_JUMP_SPRITESHEET_SOURCE[4],GameConstants.SASUKE_JUMP_SPRITESHEET_SOURCE[5]]
    self.fall_spritesheet = [self.handle_image(pygame.image.load(GameConstants.SASUKE_FALL_SPRITESHEET_SOURCE[0]).convert_alpha(),35,55,2,GameConstants.SASUKE_FALL_SPRITESHEET_SOURCE[1]),GameConstants.SASUKE_FALL_SPRITESHEET_SOURCE[1],GameConstants.SASUKE_FALL_SPRITESHEET_SOURCE[2],GameConstants.SASUKE_FALL_SPRITESHEET_SOURCE[3],GameConstants.SASUKE_FALL_SPRITESHEET_SOURCE[4],GameConstants.SASUKE_FALL_SPRITESHEET_SOURCE[5]]
    self.nomal_attack1_spritesheet = [self.handle_image(pygame.image.load(GameConstants.SASUKE_ATTACK1_SPRITESHEET_SOURCE[0]).convert_alpha(),56,48,4,GameConstants.SASUKE_ATTACK1_SPRITESHEET_SOURCE[1]),GameConstants.SASUKE_ATTACK1_SPRITESHEET_SOURCE[1],GameConstants.SASUKE_ATTACK1_SPRITESHEET_SOURCE[2],GameConstants.SASUKE_ATTACK1_SPRITESHEET_SOURCE[3],GameConstants.SASUKE_ATTACK1_SPRITESHEET_SOURCE[4],GameConstants.SASUKE_ATTACK1_SPRITESHEET_SOURCE[5]]
    self.nomal_attack2_spritesheet = [self.handle_image(pygame.image.load(GameConstants.SASUKE_ATTACK2_SPRITESHEET_SOURCE[0]).convert_alpha(),56,48,4,GameConstants.SASUKE_ATTACK2_SPRITESHEET_SOURCE[1]),GameConstants.SASUKE_ATTACK2_SPRITESHEET_SOURCE[1],GameConstants.SASUKE_ATTACK2_SPRITESHEET_SOURCE[2],GameConstants.SASUKE_ATTACK2_SPRITESHEET_SOURCE[3],GameConstants.SASUKE_ATTACK2_SPRITESHEET_SOURCE[4],GameConstants.SASUKE_ATTACK2_SPRITESHEET_SOURCE[5]]
    self.nomal_attack3_spritesheet = [self.handle_image(pygame.image.load(GameConstants.SASUKE_ATTACK3_SPRITESHEET_SOURCE[0]).convert_alpha(),62,48,4,GameConstants.SASUKE_ATTACK3_SPRITESHEET_SOURCE[1]),GameConstants.SASUKE_ATTACK3_SPRITESHEET_SOURCE[1],GameConstants.SASUKE_ATTACK3_SPRITESHEET_SOURCE[2],GameConstants.SASUKE_ATTACK3_SPRITESHEET_SOURCE[3],GameConstants.SASUKE_ATTACK3_SPRITESHEET_SOURCE[4],GameConstants.SASUKE_ATTACK3_SPRITESHEET_SOURCE[5]]
    self.hit_spritesheet = [self.handle_image(pygame.image.load(GameConstants.SASUKE_HIT_SPRITESHEET_SOURCE[0]).convert_alpha(),48,47,2,GameConstants.SASUKE_HIT_SPRITESHEET_SOURCE[1]),GameConstants.SASUKE_HIT_SPRITESHEET_SOURCE[1],GameConstants.SASUKE_HIT_SPRITESHEET_SOURCE[2],GameConstants.SASUKE_HIT_SPRITESHEET_SOURCE[3],GameConstants.SASUKE_HIT_SPRITESHEET_SOURCE[4],GameConstants.SASUKE_HIT_SPRITESHEET_SOURCE[5]]
    self.dash_spritesheet=[self.handle_image(pygame.image.load(GameConstants.SASUKE_DASH_SPRITESHEET_SOURCE[0]).convert_alpha(),48,48,6,GameConstants.SASUKE_DASH_SPRITESHEET_SOURCE[1]),GameConstants.SASUKE_DASH_SPRITESHEET_SOURCE[1],GameConstants.SASUKE_DASH_SPRITESHEET_SOURCE[2],GameConstants.SASUKE_DASH_SPRITESHEET_SOURCE[3],GameConstants.SASUKE_DASH_SPRITESHEET_SOURCE[4],GameConstants.SASUKE_DASH_SPRITESHEET_SOURCE[5]]
    super().start()