from Scripts.PlayerCharacter.Base.character_base import Character
import pygame
from Scripts.game_constants import GameConstants
from Scripts.PlayerCharacter.RockLee.State.rocklee_state_machine import RockLeeStateMachine
class RockLeeCharacter(Character):
  def __init__(self,game_scene,player_id,x,y,screen_surface,target):
    super().__init__(game_scene,player_id,x,y,screen_surface,target)
    self.rect = pygame.Rect((x,y,GameConstants.ROCKLEE_WIDTH_RECT,GameConstants.ROCKLEE_HEIGHT_RECT))
    self.state_machine = RockLeeStateMachine(self,screen_surface)

  def start(self):
    self.idle_spritesheet = [self.handle_image(pygame.image.load(GameConstants.ROCKLEE_IDLE_SPRITESHEET_SOURCE[0]).convert_alpha(),33,48,4,GameConstants.ROCKLEE_IDLE_SPRITESHEET_SOURCE[1]),GameConstants.ROCKLEE_IDLE_SPRITESHEET_SOURCE[1],GameConstants.ROCKLEE_IDLE_SPRITESHEET_SOURCE[2],GameConstants.ROCKLEE_IDLE_SPRITESHEET_SOURCE[3],GameConstants.ROCKLEE_IDLE_SPRITESHEET_SOURCE[4],GameConstants.ROCKLEE_IDLE_SPRITESHEET_SOURCE[5]]
    self.move_spritesheet = [self.handle_image(pygame.image.load(GameConstants.ROCKLEE_MOVE_SPRITESHEET_SOURCE[0]).convert_alpha(),41,40,6,GameConstants.ROCKLEE_MOVE_SPRITESHEET_SOURCE[1]),GameConstants.ROCKLEE_MOVE_SPRITESHEET_SOURCE[1],GameConstants.ROCKLEE_MOVE_SPRITESHEET_SOURCE[2],GameConstants.ROCKLEE_MOVE_SPRITESHEET_SOURCE[3],GameConstants.ROCKLEE_MOVE_SPRITESHEET_SOURCE[4],GameConstants.ROCKLEE_MOVE_SPRITESHEET_SOURCE[5]]
    self.jump_spritesheet= [self.handle_image(pygame.image.load(GameConstants.ROCKLEE_JUMP_SPRITESHEET_SOURCE[0]).convert_alpha(),25,48,2,GameConstants.ROCKLEE_JUMP_SPRITESHEET_SOURCE[1]),GameConstants.ROCKLEE_JUMP_SPRITESHEET_SOURCE[1],GameConstants.ROCKLEE_JUMP_SPRITESHEET_SOURCE[2],GameConstants.ROCKLEE_JUMP_SPRITESHEET_SOURCE[3],GameConstants.ROCKLEE_JUMP_SPRITESHEET_SOURCE[4],GameConstants.ROCKLEE_JUMP_SPRITESHEET_SOURCE[5]]
    self.fall_spritesheet = [self.handle_image(pygame.image.load(GameConstants.ROCKLEE_FALL_SPRITESHEET_SOURCE[0]).convert_alpha(),33,40,2,GameConstants.ROCKLEE_FALL_SPRITESHEET_SOURCE[1]),GameConstants.ROCKLEE_FALL_SPRITESHEET_SOURCE[1],GameConstants.ROCKLEE_FALL_SPRITESHEET_SOURCE[2],GameConstants.ROCKLEE_FALL_SPRITESHEET_SOURCE[3],GameConstants.ROCKLEE_FALL_SPRITESHEET_SOURCE[4],GameConstants.ROCKLEE_FALL_SPRITESHEET_SOURCE[5]]
    self.nomal_attack1_spritesheet = [self.handle_image(pygame.image.load(GameConstants.ROCKLEE_ATTACK1_SPRITESHEET_SOURCE[0]).convert_alpha(),51,48,4,GameConstants.ROCKLEE_ATTACK1_SPRITESHEET_SOURCE[1]),GameConstants.ROCKLEE_ATTACK1_SPRITESHEET_SOURCE[1],GameConstants.ROCKLEE_ATTACK1_SPRITESHEET_SOURCE[2],GameConstants.ROCKLEE_ATTACK1_SPRITESHEET_SOURCE[3],GameConstants.ROCKLEE_ATTACK1_SPRITESHEET_SOURCE[4],GameConstants.ROCKLEE_ATTACK1_SPRITESHEET_SOURCE[5]]
    self.nomal_attack2_spritesheet = [self.handle_image(pygame.image.load(GameConstants.ROCKLEE_ATTACK2_SPRITESHEET_SOURCE[0]).convert_alpha(),60,48,4,GameConstants.ROCKLEE_ATTACK2_SPRITESHEET_SOURCE[1]),GameConstants.ROCKLEE_ATTACK2_SPRITESHEET_SOURCE[1],GameConstants.ROCKLEE_ATTACK2_SPRITESHEET_SOURCE[2],GameConstants.ROCKLEE_ATTACK2_SPRITESHEET_SOURCE[3],GameConstants.ROCKLEE_ATTACK2_SPRITESHEET_SOURCE[4],GameConstants.ROCKLEE_ATTACK2_SPRITESHEET_SOURCE[5]]
    self.nomal_attack3_spritesheet = [self.handle_image(pygame.image.load(GameConstants.ROCKLEE_ATTACK3_SPRITESHEET_SOURCE[0]).convert_alpha(),57,48,4,GameConstants.ROCKLEE_ATTACK3_SPRITESHEET_SOURCE[1]),GameConstants.ROCKLEE_ATTACK3_SPRITESHEET_SOURCE[1],GameConstants.ROCKLEE_ATTACK3_SPRITESHEET_SOURCE[2],GameConstants.ROCKLEE_ATTACK3_SPRITESHEET_SOURCE[3],GameConstants.ROCKLEE_ATTACK3_SPRITESHEET_SOURCE[4],GameConstants.ROCKLEE_ATTACK3_SPRITESHEET_SOURCE[5]]
    self.hit_spritesheet = [self.handle_image(pygame.image.load(GameConstants.ROCKLEE_HIT_SPRITESHEET_SOURCE[0]).convert_alpha(),41,40,2,GameConstants.ROCKLEE_HIT_SPRITESHEET_SOURCE[1]),GameConstants.ROCKLEE_HIT_SPRITESHEET_SOURCE[1],GameConstants.ROCKLEE_HIT_SPRITESHEET_SOURCE[2],GameConstants.ROCKLEE_HIT_SPRITESHEET_SOURCE[3],GameConstants.ROCKLEE_HIT_SPRITESHEET_SOURCE[4],GameConstants.ROCKLEE_HIT_SPRITESHEET_SOURCE[5]]
    self.dash_spritesheet = [self.handle_image(pygame.image.load(GameConstants.ROCKLEE_DASH_SPRITESHEET_SOURCE[0]).convert_alpha(),33,48,4,GameConstants.ROCKLEE_DASH_SPRITESHEET_SOURCE[1]),GameConstants.ROCKLEE_DASH_SPRITESHEET_SOURCE[1],GameConstants.ROCKLEE_DASH_SPRITESHEET_SOURCE[2],GameConstants.ROCKLEE_DASH_SPRITESHEET_SOURCE[3],GameConstants.ROCKLEE_DASH_SPRITESHEET_SOURCE[4],GameConstants.ROCKLEE_DASH_SPRITESHEET_SOURCE[5]]
    
    self.skill1_spritesheet =[self.handle_image(pygame.image.load(GameConstants.ROCKLEE_SKILL1_SPRITESHEET_SOURCE[0]).convert_alpha(),73,65,7,GameConstants.ROCKLEE_SKILL1_SPRITESHEET_SOURCE[1]),GameConstants.ROCKLEE_SKILL1_SPRITESHEET_SOURCE[1],GameConstants.ROCKLEE_SKILL1_SPRITESHEET_SOURCE[2],GameConstants.ROCKLEE_SKILL1_SPRITESHEET_SOURCE[3],GameConstants.ROCKLEE_SKILL1_SPRITESHEET_SOURCE[4],GameConstants.ROCKLEE_SKILL1_SPRITESHEET_SOURCE[5]]
    self.skill2_spritesheet =[self.handle_image(pygame.image.load(GameConstants.ROCKLEE_SKILL2_SPRITESHEET_SOURCE[0]).convert_alpha(),96,65,6,GameConstants.ROCKLEE_SKILL2_SPRITESHEET_SOURCE[1]),GameConstants.ROCKLEE_SKILL2_SPRITESHEET_SOURCE[1],GameConstants.ROCKLEE_SKILL2_SPRITESHEET_SOURCE[2],GameConstants.ROCKLEE_SKILL2_SPRITESHEET_SOURCE[3],GameConstants.ROCKLEE_SKILL2_SPRITESHEET_SOURCE[4],GameConstants.ROCKLEE_SKILL2_SPRITESHEET_SOURCE[5]]
    super().start()